### ISSUE TITLE
Inconsistent description for HTTPCode_ELB_5XX metric

### ISSUE THREAD

**Issue by lukaszjankowski** [awsdocs/elb-classic-load-balancers-user-guide#3]
Description for troubleshooting [HTTPCode_ELB_5XX](https://github.com/awsdocs/elb-classic-load-balancers-user-guide/blob/master/doc_source/ts-elb-http-errors.md#httpcode_elb_5xx) metric says:

> Cause: Either the load balancer or the registered instance is causing the error or the load balancer is unable to parse the response.

while in [CloudWatch docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-cloudwatch-metrics.html) say:

> The number of HTTP 5XX server error codes generated by the load balancer. This count does not include any response codes generated by the registered instances. The metric is reported if there are no healthy instances registered to the load balancer, or if the request rate exceeds the capacity of the instances (spillover) or the load balancer.

Which version is correct? Does `HTTPCode_ELB_5XX` include errors from registered instances, or are they related to only ELB itself?

**Comment by julieso** [comment]
The cause can be an issue in the instance or load balancer, as documented here: https://github.com/awsdocs/elb-classic-load-balancers-user-guide/blob/master/doc_source/ts-elb-http-errors.md#ts-elb-error-metrics-ELB_5XX. Whether the issue is with the load balancer or the instance, the load balancer generates an HTTP 5XX error. The description of HTTPCode_ELB_5XX clarifies that it is a count of the error codes generated by the load balancer. If the instance also generates HTTP 5XX errors under the same circumstance, they are not reported in the HTTPCode_ELB_5XX metric, they are counted in HTTPCode_Backend_5XX.
